name: Deploy to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Deploy to Azure Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name mysotoragere34122 --auth-mode key --destination '$web' --source ./dist
      env:
        AZURE_STORAGE_ACCOUNT: mysotoragere34122
        AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}